# Generated by Django 3.2 on 2021-05-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('subheading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('categery', models.CharField(max_length=100)),
                ('google', models.BooleanField(default=False)),
                ('microsoft', models.BooleanField(default=False)),
                ('socialmedia', models.BooleanField(default=False)),
                ('adobe', models.BooleanField(default=False)),
                ('apple', models.BooleanField(default=False)),
                ('Other', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
