# Generated by Django 3.2 on 2021-05-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcutrofin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav',
            name='categery1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='fav',
            name='categery2',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
