# Generated by Django 3.2 on 2021-05-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcutrofin', '0002_auto_20210516_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fav',
            old_name='categery',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='fav',
            old_name='categery1',
            new_name='category1',
        ),
        migrations.RenameField(
            model_name='fav',
            old_name='categery2',
            new_name='category2',
        ),
    ]
