# Generated by Django 3.2 on 2021-12-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcutrofin', '0003_auto_20210516_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fav',
            new_name='All',
        ),
    ]
