# Generated by Django 3.2 on 2021-12-30 16:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alcutrofin', '0005_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='favorite',
            new_name='favourite',
        ),
    ]
