# Generated by Django 3.2 on 2021-12-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcutrofin', '0006_rename_favorite_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='postid',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='userid',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
