# Generated by Django 3.2 on 2021-12-30 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alcutrofin', '0010_auto_20211230_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='favourite',
            field=models.ManyToManyField(related_name='Favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
