# Generated by Django 3.2 on 2021-12-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcutrofin', '0011_auto_20211230_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='url',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
